############################ DON'T CHANGE ANYTHING IN HERE - USE THE .env FILE! ############################

version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - "./docker_volumes/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"

  beelogger:
    image: ghcr.io/programmier-ag/beelogger:latest
    # Uncomment if you'd like to build the image yourself.
    # build: .
    depends_on:
      - db
    restart: "no"
    ports:
      - 2688:8000
    volumes:
      - "./docker_volumes/contact:/app/contact"
      - "./docker_volumes/backup:/app/backup"
      - "./docker_volumes/logs:/app/logs"
      - "./docker_volumes/secrets:/app/secrets"
    environment:
      telegram_bot_token: "${telegram_bot_token}"

      insert_token: "${insert_token}"
      display_token: "${display_token}"

      correction: '${correction}'
      tare: '${tare}'
      real_tare: '${real_tare}'

      mysql_host: "${mysql_host}"
      mysql_port: "${mysql_port}"
      mysql_user: "${mysql_user}"
      mysql_pass: "${mysql_pass}"
      mysql_db: "${mysql_db}"

      pages: '${pages}'

      mysql_backup_host: "${mysql_backup_host}"
      mysql_backup_port: "${mysql_backup_port}"
      mysql_backup_user: "${mysql_backup_user}"
      mysql_backup_pass: "${mysql_backup_pass}"
      mysql_backup_db: "${mysql_backup_db}"

      backup_host: "${backup_host}"
      backup_port: "${backup_port}"
      backup_user: "${backup_user}"
      backup_pass: "${backup_pass}"
      backup_key: "${backup_key}"
      backup_dir: "${backup_dir}"

      mail_host: "${mail_host}"
      mail_port: "${mail_port}"
      mail_user: "${mail_user}"
      mail_pass: "${mail_pass}"
      mail_rec: "${mail_rec}"
