version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306
    volumes:
      - "./docker_volumes/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "changeme!1"

  beelogger:
    image: ghcr.io/programmier-ag/beelogger:latest
    # Uncomment if you'd like to build the image yourself.
    # build: .
    depends_on:
      - db
    restart: "no"
    ports:
      - 2688:8000
    volumes:
      - "./docker_volumes/contact:/app/contact"
      - "./docker_volumes/backup:/app/backup"
      - "./docker_volumes/logs:/app/logs"
      - "./docker_volumes/secrets:/app/secrets"
    environment:
      telegram_bot_token: ""

      insert_token: "changeme!2"
      display_token: "changeme!3"

      correction: '{"0": 1}'
      tare: '{"0": 0}'
      real_tare: '{"0": 0}'

      mysql_host: "db"
      mysql_port: "3306"
      mysql_user: "root"
      mysql_pass: "changeme!1"
      mysql_db: "beelogger"

      pages: '{}'

      mysql_backup_host: ""
      mysql_backup_port: "3306"
      mysql_backup_user: ""
      mysql_backup_pass: ""
      mysql_backup_db: ""

      backup_host: ""
      backup_port: "22"
      backup_user: ""
      backup_pass: ""
      backup_key: ""
      backup_dir: ""

      mail_host: ""
      mail_port: "465"
      mail_user: ""
      mail_pass: ""
      mail_rec: ""
